# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

#target 'googleMapsPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
pod 'GoogleMaps'

  # Pods for googleMapsPractice
  source 'https://github.com/CocoaPods/Specs.git'
  target 'YOUR_APPLICATION_TARGET_NAME_HERE' do
    pod 'GooglePlaces'
end
